### ISSUE TITLE
GitOps with Flux - PostDeploy work

### ISSUE THREAD

**Issue by Gordonby** [Azure/AKS-Construction#293]
Extension of #288  - This one is all about eating our own dogfood

## Todo
- [ ] Adding POSTDEPLOY Flux gitops config to a directory in this repo (ExternalDNS / Cert Manager / Etc)
- [ ] Add Flux to one of the CI/CD workflows
- [ ] Use [AZ extensions](https://docs.microsoft.com/en-us/azure/azure-arc/kubernetes/tutorial-use-gitops-flux2#enable-cli-extensions) in the CI/CD workflows that test flux is working
